pyTorch Fundamental

In [1]:
!nvidia-smi

Mon Mar 27 16:13:43 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.41                 Driver Version: 531.41       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 L...  WDDM | 00000000:01:00.0  On |                  N/A |
| N/A   40C    P5                6W /  N/A|    198MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0


In [3]:
# scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 6, 9],
        [2, 4, 5]])

In [16]:
# random tensor
random_tensor = torch.rand(3, 4)
random_tensor = torch.rand(10, 10)
random_tensor = torch.rand(1, 3, 4)

random_tensor

tensor([[[0.5813, 0.1796, 0.7544, 0.4160],
         [0.7751, 0.8942, 0.1978, 0.6159],
         [0.4725, 0.3426, 0.3680, 0.6756]]])

In [17]:
random_tensor.ndim

3

In [18]:
# ceating a ramdom tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244, 224, 3)) #height, with, colour channel(R, G, B) or colour channel(R, G, B), with, height 
random_image_size_tensor.shape, random_image_size_tensor.ndim 

(torch.Size([244, 224, 3]), 3)

In [19]:
# create a tensor of zeros and one
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])