# PyTorch Fundamental

In [1]:
!nvidia-smi

Sat Apr  1 20:55:09 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.41                 Driver Version: 531.41       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 L...  WDDM | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P0               15W /  N/A|      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0


In [3]:
# scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 6, 9],
        [2, 4, 5]])

In [16]:
# random tensor
random_tensor = torch.rand(3, 4)
random_tensor = torch.rand(10, 10)
random_tensor = torch.rand(1, 3, 4)

random_tensor

tensor([[[0.7787, 0.4297, 0.5860, 0.1930],
         [0.2504, 0.8590, 0.2633, 0.7513],
         [0.3934, 0.5619, 0.6266, 0.6887]]])

In [17]:
random_tensor.ndim

3

In [18]:
# ceating a ramdom tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244, 224, 3)) #height, with, colour channel(R, G, B) or colour channel(R, G, B), with, height 
random_image_size_tensor.shape, random_image_size_tensor.ndim 

(torch.Size([244, 224, 3]), 3)

In [19]:
# create a tensor of zeros and one
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
# create tensor of one
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
one.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

In [24]:
# creating a range of tensors and tensors-like
# using torch.range()
torch.range(0, 10)

C:\Users\user\AppData\Local\Temp\ipykernel_15072\1260213167.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
# using torch.arange
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
torch.arange(start = 0, end = 1000, step = 50)

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [27]:
# creating tensors like
one_to_ten = torch.arange(start = 1, end = 10, step = 1)
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

## tensor datatypes
### Tensos not right datatype
### Tensor not right shape
### tensor not on the right device

In [28]:

# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None,#what datatype is the tensor e.g.float32 or float16
                              device = None,
                              requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## getting information from tensors (tensor attributes)
### Tensos not right datatype - to get datatype from a tensor, can use tensor.dtype
### Tensor not right shape - to get shape from a tensor, can use tensor.shape
### tensor not on the right device - to get device from a tensor, can use tensor.device


In [36]:

# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0074, 0.5328, 0.5250, 0.8629],
        [0.3603, 0.3044, 0.0901, 0.1512],
        [0.2622, 0.7046, 0.8909, 0.0848]])

In [37]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [38]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype od tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.0074, 0.5328, 0.5250, 0.8629],
        [0.3603, 0.3044, 0.0901, 0.1512],
        [0.2622, 0.7046, 0.8909, 0.0848]])
Datatype od tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


# Manipulating Tensors (tensor operation)
# Tensor operation include:
###     addition
###     subtraction
###     multiplication(element-wise)
###     divison
###     matrix multiplication

In [39]:


# creat a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# try out PyTorch in_built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# matrix multiplication
## two main ways of performing multipacation in neural networks and deep learning:
### 1.Element-wise multiplication
### 2.Matrix multiplication(dot product)

In [44]:

# element wise multiplication
print(tensor, "*" , tensor )
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [45]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
Wall time: 6.01 ms


In [47]:
tensor @ tensor

tensor(14)

In [48]:
%%time
torch.matmul(tensor, tensor)

Wall time: 0 ns


tensor(14)

In [50]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## To fix our tensor shape issues, we can manipulate the shape of one our tensor using a transpose

In [51]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [52]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [53]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum ....

In [54]:
# creating a tensor
x = torch.arange(0,100, 10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [55]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
# find the mean torch
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## finding the positional min and max

In [58]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
# finding the positionn of min value
x.argmin()

tensor(0)

In [60]:
x[0]

tensor(0)

In [61]:
x.argmax()

tensor(9)

In [62]:
x[9]

tensor(90)

## reshaping, stacking, squeezing and unsqueezing tensor
#### Reshaping - reshapes an input tensor to defined shape
#### view - Return a view of an input tensor of certain shape but keep the memory
#### Stacking - combine all multiple tensors on top of each other(vstack) or side (hstack)
#### squeeze - remove all `1` dimension from tensor
#### unsquee - add a dimension to target tensor
#### permute - return a view of the input with dimensions permuted(swapped) in certain way

In [67]:
# let's create a tensor
import torch
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [77]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [80]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [84]:
# stack tensors on top of each other 
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])